name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./typescript

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit
