name: Canary Release

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./typescript

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./typescript/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "./typescript/pnpm-lock.yaml"

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Configure NPM Auth Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Create Snapshot
        id: create_snapshot
        run: pnpm changeset version --snapshot latest || echo "No unreleased changesets found"

      - name: Check for Changeset
        id: check_changeset
        run: echo "changeset_exists=$(grep -q 'No unreleased changesets found' <<< '${{ steps.create_snapshot.outputs.stdout }}' && echo false || echo true)" >> $GITHUB_ENV

      - name: Build
        if: env.changeset_exists == 'true'
        run: pnpm build

      - name: Publish Snapshot
        if: env.changeset_exists == 'true'
        run: pnpm changeset publish --snapshot --tag latest --no-git-tag
