name: "Verify"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Setup Environment Variables
        shell: bash
        run: |
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
          echo "ACCOUNT=${{ vars.ACCOUNT }}" >> .env
          echo "ADDRESS=${{ vars.ADDRESS }}" >> .env

      - name: Run Tests
        run: pnpm test
